name: Workflow
on: [push]

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: nanasess/setup-php@master
        with:
          php-version: '7.4'
      - name: Install Dependencies
        run: composer install
      - name: Install Faker
        run: composer require fzaninotto/faker
      - name: Run chromedriver
        run: |
          export DISPLAY=:99
          chromedriver --headless --no-sandbox --disable-dev-shm-usage --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
      - name: Run tests
        run: php vendor/bin/codecept run --steps -vvv --xml
      - name: JUnit Report Action
        if: always()
        uses: mikepenz/action-junit-report@v2.4.2
        with:
          report_paths: 'tests/_output/report.xml'
